name: circuito_rpg
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Project dependencies
  get_it: ^7.2.0
  provider: ^6.0.5
  http: ^0.13.6
  dartz: ^0.10.1
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # Assets
  assets:
    - assets/images/banner.jpg
    - assets/images/sobre.jpg
    - assets/images/export.jpg
